### ISSUE TITLE
Items deleted

### ISSUE THREAD

**Issue by eviltek2099** [MSchmoecker/ValheimHopper#10]
Tested with Charcoal Kilm and Smelter. 
When attached to the import items going through the bronze side hopper they are not inserted into the machine they are attached to. I have tried setting Item dropping but same result. 
Running Ashland preview exe version 2022.3.17f1 (4#fc78088f837)

**Comment by MSchmoecker** [comment]
The Ashlands update renames some important network messages for the smelter. Specifically `AddOre` to `RPC_AddOre` and `AddFuel` to `RPC_AddFuel`, thus breaking the mod.
Will be fixed ones Ashlands is released because the change is not backwards compatible

**Comment by MSchmoecker** [comment]
Fixed with 1.5.0
