### ISSUE TITLE
Issue: Hoppers do not interact with Item Drawers

### ISSUE THREAD

**Issue by Karmacopper** [MSchmoecker/ValheimHopper#16]
Cannot insert or retrieve from [KGValheim Item Drawers](https://thunderstore.io/c/valheim/p/KGvalheim/ItemDrawers/)

**Comment by MSchmoecker** [comment]
This is known, however no support is planned at the moment.

The problem is that his drawers aren't containers but use a custom script. This requires significant work to make both mods compatible, without having edge cases that could lead to item loss.
