### ISSUE TITLE
Snap Point

### ISSUE THREAD

**Issue by whoiamiamanonym** [MSchmoecker/ValheimHopper#2]
![image](https://user-images.githubusercontent.com/89044900/193529321-74d553c6-39d8-4792-850c-4312c324de48.png)
When I put the iron side hopper here, it breaks (because there is no support)
If I put the beam on top like this ![image](https://user-images.githubusercontent.com/89044900/193529791-b137c92d-60d8-4f45-a826-d6ceff616ed7.png), it's fine.

**Comment by MSchmoecker** [comment]
Thanks, the snappoints were slightly too far away from the furnace and thus had no support. Will fix this quickly

**Comment by MSchmoecker** [comment]
Fixed in 0.3.1

**Comment by whoiamiamanonym** [comment]
Thank you)
