### ISSUE TITLE
Suggestions for pipes

### ISSUE THREAD

**Issue by Karmacopper** [MSchmoecker/ValheimHopper#5]
Now the new pipes are released, I have a couple of suggestions for QoL.

Vertical pipes. Although gizmo rotation mods appear to take care of this.

1 meter pipe, to allow more compact builds.

Pipe filter, to allow routing of multiple item types through the pipe network.

**Comment by MSchmoecker** [comment]
Everything besides pipe filtering has been implemented in the last few updates but that's still planned. It will probably use the same filtering as the hoppers, it's kinda a pain pipes can't be filtered at the moment.

**Comment by MSchmoecker** [comment]
This can be closed now, pipes behave like hoppers in 2.0.0
