### ISSUE TITLE
Item Duplication using Hopper mod and Drawer mod

### ISSUE THREAD

**Issue by 1kili2** [MSchmoecker/ValheimHopper#6]
I believe this issue might lay more on the side of the itemsDrawer mod [https://valheim.thunderstore.io/package/makail/ItemDrawers/](url) and although they seem to implement compatibility fixes I can't find a way to contact them so I'm posting the issue here because the Hoppers mod is the only way to reproduce this issue.

When filling an empty item drawer from a pipe the number on the drawer will go up but no actual item will be displayed, this wouldn't seem like an issue at first but now I can input any item into the drawer it will add the amount I put in to the number already displayed and turn all the existing things in the drawer into the new item I just manually put in, so lets say I pipe in 50 stone, the drawer knows there's 50 but not 50 of what, then I manually put in 1 fine wood and now I have 51 fine wood

**Comment by MSchmoecker** [comment]
Fixed in MultiUserChest 0.5.6
