### ISSUE TITLE
Suggestion for checkbox on hoppers to leave last item in chest

### ISSUE THREAD

**Issue by FractusNine** [MSchmoecker/ValheimHopper#8]
Just thought of one more suggestion -- 
it would be great to have an option to always leave the last item in a chest when pulling items. 

Here is the use case I had in mind --
I've set up hoppers from a chest with bolts to a set of ballistas, but as soon as the bolts get used up, quickstack doesn't stack to the original chest any longer (since it doesn't have the original item in it). 

Thanks again for the mod, and for considering this possibility!

**Comment by MSchmoecker** [comment]
Thanks for the suggestion, added in 2.0.0
