### ISSUE TITLE
Crash when hoppers place items

### ISSUE THREAD

**Issue by SuperSid2007** [MSchmoecker/ValheimHopper#9]
Seems like after i placed hoppers down when someone opens one of my chests or the hoppers place an item in a chest ive created in crashes my game I dont even need to be near them when they open it

**Comment by MSchmoecker** [comment]
Please provide your log files from BepInEx/LogOut.log from both players after this happened

**Comment by MSchmoecker** [comment]
Closing this without further information. Feel free to reopen if this still occurs and you can provide more information.
